// #include <ArduinoLowPower.h>
#include <SPI.h>
#include <LoRa.h>

const double MAX_EMF_VOLTAGE = 15.0;
const double MAX_ACC_VOLTAGE = 3.3;
int counter = 0;

void setup() {
  Serial.begin(9600);
  while (!Serial);

  Serial.println("LoRa Sender");

  // halts program if lora failed to start
  if (!LoRa.begin(868E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

double gen_voltage(int counter) {
  /* Generates a simulated value for emf voltage generated by generator */

  return MAX_EMF_VOLTAGE * sin(counter);
}

double gen_accelerometer(int counter) {
  /* Generates a simulated value for voltage generated by accelerometer */

	return MAX_ACC_VOLTAGE * cos(counter);
}

void loop() {
  Serial.print("Sending packet: ");

  // generates simulated data values
  double emf_volt = gen_voltage(counter);
  double acc_volt = gen_accelerometer(counter);
  Serial.println(emf_volt);
  Serial.println(acc_volt);

  // sends packet with data
  LoRa.beginPacket();
  LoRa.print(emf_volt);
  LoRa.print(" "); // space is used to separate each data value
  LoRa.print(acc_volt);
  LoRa.endPacket();

  // advances counter
  counter++;

  // delays/waits for 0.5s
  delay(500);
}