name: Issue States

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
      runs-on: ubuntu-latest
      steps:
        - uses: dessant/issue-states@v3.0.0
          with:
            # Reopen issues that are moved to these project columns, value must be a comma separated list of project columns
            open-issue-columns: 'Todo, In Progress'  # optional, default is ''
            # Close issues that are moved to these project columns, value must be a comma separated list of project columns
            closed-issue-columns: 'Closed, Done' # optional, default is 'Closed, Done'
            # Log output parameters, value must be either `true` or `false`
            log-output: false  # optional, default is false
